---
- name: Converge
  hosts: all
  tasks:
    - name: Include dtrdnk.yum_repos
      include_role:
        name: dtrdnk.yum_repos
    - name: Update cache
      ansible.builtin.dnf:
        update_cache: true
    - name: Install test package
      ansible.builtin.dnf:
        name: nmon
        state: present
  vars_files:
    - rhel8.yml
